language: c
compiler:
  - gcc
# - clang

before_install:
  # Get CMake >=2.8.8, HDF5 >= 1.8.6
  - sudo add-apt-repository -y ppa:amcg/netcdf-parallel
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq cmake libhdf5-dev libhdf4-dev libcurl4-openssl-dev m4

before_script:
    - mkdir build && cd build
    - cmake .. -DENABLE_EXTRA_TESTS=ON -DENABLE_HDF4=ON

script:
  - make && make test
