sudo: required
language: c
services:
    - docker

env:
    matrix:
        - DOCKIMG=unidata/nctests:serial


before_install:
    - docker pull $DOCKIMG

script:
    - docker run --rm -it -e USEDASH=OFF -e RUNF=OFF -e RUNCXX=OFF -e RUNP=OFF -e RUNNCO=OFF -e USEAC=OFF -v $(pwd):/netcdf-c $DOCKIMG