sudo: required
language: c
services:
    - docker

env:
    matrix:
        - DOCKIMG=unidata/nctests:serial   USECMAKE=TRUE USEAC=TRUE DISTCHECK=TRUE USE_CC=gcc   COPTS='-DCMAKE_C_FLAGS=-fsigned-char -DENABLE_NETCDF_4=OFF -DENABLE_DAP=OFF' CURHOST=docker-nc3-gcc-x64-signed
        - DOCKIMG=unidata/nctests:serial   USECMAKE=TRUE USEAC=TRUE DISTCHECK=TRUE USE_CC=clang COPTS='-DCMAKE_C_FLAGS=-fsigned-char -DENABLE_NETCDF_4=OFF -DENABLE_DAP=OFF' CURHOST=docker-nc3-clang-x64-signed
        - DOCKIMG=unidata/nctests:serial32 USECMAKE=TRUE USEAC=TRUE DISTCHECK=TRUE USE_CC=gcc   COPTS='-DCMAKE_C_FLAGS=-fsigned-char -DENABLE_NETCDF_4=OFF -DENABLE_DAP=OFF' CURHOST=docker-nc3-gcc-x86-signed
        - DOCKIMG=unidata/nctests:serial32 USECMAKE=TRUE USEAC=TRUE DISTCHECK=TRUE USE_CC=clang COPTS='-DCMAKE_C_FLAGS=-fsigned-char -DENABLE_NETCDF_4=OFF -DENABLE_DAP=OFF' CURHOST=docker-nc3-clang-x86-signed

        - DOCKIMG=unidata/nctests:serial   USECMAKE=TRUE USEAC=TRUE DISTCHECK=TRUE USE_CC=gcc   COPTS='-DCMAKE_C_FLAGS=-funsigned-char -DENABLE_NETCDF_4=OFF -DENABLE_DAP=OFF' CURHOST=docker-nc3-gcc-x64-unsigned
        - DOCKIMG=unidata/nctests:serial   USECMAKE=TRUE USEAC=TRUE DISTCHECK=TRUE USE_CC=clang COPTS='-DCMAKE_C_FLAGS=-funsigned-char -DENABLE_NETCDF_4=OFF -DENABLE_DAP=OFF' CURHOST=docker-nc3-clang-x64-unsigned
        - DOCKIMG=unidata/nctests:serial32 USECMAKE=TRUE USEAC=TRUE DISTCHECK=TRUE USE_CC=gcc   COPTS='-DCMAKE_C_FLAGS=-funsigned-char -DENABLE_NETCDF_4=OFF -DENABLE_DAP=OFF' CURHOST=docker-nc3-gcc-x86-unsigned
        - DOCKIMG=unidata/nctests:serial32 USECMAKE=TRUE USEAC=TRUE DISTCHECK=TRUE USE_CC=clang COPTS='-DCMAKE_C_FLAGS=-funsigned-char -DENABLE_NETCDF_4=OFF -DENABLE_DAP=OFF' CURHOST=docker-nc3-clang-x86-unsigned

        - DOCKIMG=unidata/nctests:serial   USECMAKE=TRUE USEAC=TRUE DISTCHECK=TRUE USE_CC=gcc   COPTS='-DCMAKE_C_FLAGS=-fsigned-char -DENABLE_NETCDF_4=ON -DENABLE_DAP=ON' CURHOST=docker-nc4-dap-gcc-x64-signed
        - DOCKIMG=unidata/nctests:serial   USECMAKE=TRUE USEAC=TRUE DISTCHECK=TRUE USE_CC=clang COPTS='-DCMAKE_C_FLAGS=-fsigned-char -DENABLE_NETCDF_4=ON -DENABLE_DAP=ON' CURHOST=docker-nc4-dap-clang-x64-signed
        - DOCKIMG=unidata/nctests:serial32 USECMAKE=TRUE USEAC=TRUE DISTCHECK=TRUE USE_CC=gcc   COPTS='-DCMAKE_C_FLAGS=-fsigned-char -DENABLE_NETCDF_4=ON -DENABLE_DAP=ON' CURHOST=docker-nc4-dap-gcc-x86-signed
        - DOCKIMG=unidata/nctests:serial32 USECMAKE=TRUE USEAC=TRUE DISTCHECK=TRUE USE_CC=clang COPTS='-DCMAKE_C_FLAGS=-fsigned-char -DENABLE_NETCDF_4=ON -DENABLE_DAP=ON' CURHOST=docker-nc4-dap-clang-x86-signed

        - DOCKIMG=unidata/nctests:serial   USECMAKE=TRUE USEAC=TRUE DISTCHECK=TRUE USE_CC=gcc   COPTS='-DCMAKE_C_FLAGS=-funsigned-char -DENABLE_NETCDF_4=ON -DENABLE_DAP=ON' CURHOST=docker-nc4-dap-gcc-x64-unsigned
        - DOCKIMG=unidata/nctests:serial   USECMAKE=TRUE USEAC=TRUE DISTCHECK=TRUE USE_CC=clang COPTS='-DCMAKE_C_FLAGS=-funsigned-char -DENABLE_NETCDF_4=ON -DENABLE_DAP=ON' CURHOST=docker-nc4-dap-clang-x64-unsigned
        - DOCKIMG=unidata/nctests:serial32 USECMAKE=TRUE USEAC=TRUE DISTCHECK=TRUE USE_CC=gcc   COPTS='-DCMAKE_C_FLAGS=-funsigned-char -DENABLE_NETCDF_4=ON -DENABLE_DAP=ON' CURHOST=docker-nc4-dap-gcc-x86-unsigned
        - DOCKIMG=unidata/nctests:serial32 USECMAKE=TRUE USEAC=TRUE DISTCHECK=TRUE USE_CC=clang COPTS='-DCMAKE_C_FLAGS=-funsigned-char -DENABLE_NETCDF_4=ON -DENABLE_DAP=ON' CURHOST=docker-nc4-dap-clang-x86-unsigned

before_install:
    - docker pull $DOCKIMG > /dev/null

script:

    - docker run --rm -it -h "$CURHOST" -e USEDASH=FALSE -e RUNF=OFF -e RUNCXX=OFF -e RUNP=OFF -e RUNNCO=OFF -e USECMAKE=$USECMAKE -e USEAC=$USEAC -e DISTCHECK=$DISTCHECK -e COPTS="$COPTS" -e CTEST_OUTPUT_ON_FAILURE=1 -v $(pwd):/netcdf-c $DOCKIMG
