sudo: required
language: c
services:
    - docker

before_install:
    - docker pull unidata/nctests:serial

script:
    - docker run -e USEDASH=OFF -e RUNF=OFF -e RUNCXX=OFF -e RUNP=OFF -e RUNNCO=OFF -e USEAC=ON -v $(pwd):/netcdf-c unidata/nctests:serial